```{r setup,eval=TRUE,echo=FALSE}
if (!exists("indent")) {
	indent = '#' # ugly hack so _regression_summary can be "spun" (variables included via `r ` have to be available)
}
if (exists("testing")) {
	item = 1:10
}
item_info = attributes(item)$item
item_name = item_info$name
item_label = ifelse(is.null(item_info$label), "", item_info$label)
choices = attributes(item)$labels
```

`r indent`## `r item_name` {#`r item_name` .tabset}

`r indent`### Distribution {#`r item_name`_distribution}
```{r distribution}
old_height = knitr::opts_chunk$get("fig.height")
if ( !is.numeric(item) ) {
	if (is.null(choices) || dplyr::n_distinct(na.omit(item)) > length(choices)) {
		choices = unique(item)
		names(choices) = choices
	}
	new_height = 1.5 * length(choices)
	new_height = ifelse(new_height > 20, 20, new_height)
	new_height = ifelse(new_height < 1, 1, new_height)
	knitr::opts_chunk$set(fig.height = new_height)
}

wrap_at = knitr::opts_chunk$get("fig.width") * 10
```
```{r}
# numeric items are plotted horizontally (because that's what usually expected)
# categorical items are plotted vertically because we can use the screen real estate better this way
# todo: if there are free-text choices mingled in with the pre-defined ones, don't show
# todo: show rare items if they are pre-defined
# todo: bin rare responses into "other category"
if (is.numeric(item) || dplyr::n_distinct(item) < 20) {
	dist_plot = ggplot2::ggplot() +
		ggplot2::geom_bar(ggplot2::aes(x = item)) +
		ggplot2::stat_bin() + 
		ggplot2::ggtitle(item_name, subtitle = stringr::str_wrap(item_label, width = wrap_at))

	if (!is.null(choices) &&
			dplyr::n_distinct(item) < 13 && 
			is.numeric(choices) && 
			any(names(choices) != unlist(choices))) {
		dist_plot = dist_plot + ggplot2::scale_x_discrete("Choices", labels = stringr::str_wrap(names(choices), 15), limits = choices)
	} else if (!is.null(choices)) {
		dist_plot = dist_plot + ggplot2::scale_x_discrete("Choices", limits = choices, labels = stringr::str_wrap(as.character(choices), 20))
	}

	if ( !is.numeric(item) ) {
		dist_plot = dist_plot + ggplot2::coord_flip()
	}
	

	dist_plot
} else {
	cat(dplyr::n_distinct(item), " unique, categorical values, so not shown.")
}
knitr::opts_chunk$set(fig.height = old_height)
```

`r indent`### Summary statistics {#`r item_name`_summary}
```{r summary}
if (haven::is.labelled(scale)) {
  item = haven::as_factor(item, levels = 'both')
}
pander::pander(skimr::skim_v(item))
```

`r indent`### Item {#`r item_name`_item}

```{r items}
item_info$label_parsed = item_info$choices = item_info$choice_list = item_info$study_id = item_info$id = NULL
pander::pander(as.data.frame(t(item_info)))
```



`r indent`#### Labels {#`r item_name`_labels}
```{r choices}
if (!is.null(choices) && length(choices) < 20) {
	pander::pander(choices)
}
```

