```{r setup,eval=TRUE,echo=FALSE}
if (!exists("indent")) {
	indent = '#' # ugly hack
}
if (exists("testing")) {
	results = data.frame()
	survey_repetition = 'single'
	reliabilities = list()
	missingness_report = TRUE
}
```

`r indent`# Survey overview

```{r}
if(! (exists("session", results) &&
    exists("created", results) &&
    exists("ended", results) &&
    exists("expired", results) &&
    exists("modified", results))) {
    warning("The variables session, created, ended, expired, modified have to be defined for automatic survey duration calculations to work.")
} else {
  codebook_survey_overview(results, survey_repetition)
}
```



`r indent`# Scales

```{r scales,results='asis'}
vars = names(results)
for (i in seq_along(vars)) {
	var = vars[i]
	scale = results[[ var ]]
	scale_info = attributes(scale)
	if ( !is.null(scale_info) && exists("scale", scale_info)) {
	  cat(codebook_component_scale( scale, dplyr::select(results, .data$session, dplyr::starts_with(scale_info$scale)), reliabilities[[var]], indent))
	}
}
```

`r indent`# Single items

```{r items,results='asis'}
for (i in seq_along(vars)) {
	var = vars[i]
	item = results[[ var ]]
	item_info = attributes(item)
	if ( !is.null(item_info)) {
		if (exists("part_of_scale", item_info) || exists("scale", item_info) || var %in% c("created", "modified", "expired", "ended")) {
			next
		} else if (exists("item", item_info)) {
			cat(codebook_component_single_item( item, results, indent ))
		} else {
			cat(codebook_component_fallback( item, results, var, indent))
		}
	}
}
```


`r indent`# Missingness report {.tabset .tabset-sticky}

### Missingness finishers

among those who finished the survey

```{r missingness_all_setup}
if (missingness_report) {
  if (  exists("ended", results) &&
    exists("expired", results)) {
    finisher_results = dplyr::select(dplyr::filter(results, !is.na(ended)), -.data$expired, -.data$ended) 
  } else {
    finisher_results = results
    warning("Could not figure out who finished the surveys, because the variables expired and ended were missing.")
  }
  missingness = formr::missingness_patterns(finisher_results)
}
```
```{r missingness_all}
if (missingness_report) {
  pander::pander(dplyr::filter(missingness, .data$Freq > 9))
} else {
  cat("No missingness report requested.")
}
```



### Missingness starters

among those who started the survey. Only patterns occuring at least 10 times are shown.

```{r missingness_starters_setup,results='markup'}
if (exists("modified", results) && missingness_report) {
  missingness = formr::missingness_patterns(
  	dplyr::filter(results, !is.na(modified)) )
} else if (!exists("modified", results)) {
  cat("Did not track who started the survey.")
} else {
  cat("No missingness report requested.")
}
```
```{r missingness_starters}
if (exists("modified", results) && missingness_report) {
  pander::pander(dplyr::filter(missingness, .data$Freq > 9))
} else if (!exists("modified", results)) {
  cat("Did not track who started the survey.")
} else {
  cat("No missingness report requested.")
}
```


### Item table
```{r}
items = formr::items(results)
if (length(items)) {
  item_index = dplyr::select(as.data.frame(items), -.data$choice_list, -.data$index)
  item_index = dplyr::mutate(item_index, name = paste0('<a href="#', .data$name, '">', .data$name, '</a>'))
  DT::datatable(item_index, rownames = FALSE, filter = "top", extensions = 'Buttons', 
  escape = setdiff(names(item_index), 'name'),
  options = list(
      dom = 'Bfrtip',
      buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
      pageLength = 200
    ))
} else {
  cat("No items encoded in metadata.")
}
```
